kind: Service
apiVersion: v1
metadata:
  name: dictionary-server-lb
spec:
  type: LoadBalancer
  selector:
    app: dictionary-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080